# Generated by Django 4.0.4 on 2022-06-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_mensaje_avatar_alter_pelicula_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.CharField(max_length=40),
        ),
    ]
