# Generated by Django 4.0.4 on 2022-06-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='id_clase',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
