# Generated by Django 4.0.4 on 2022-06-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_mensaje_id_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
