# Generated by Django 4.0.4 on 2022-06-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_pelicula_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='clase',
            field=models.CharField(default='L', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='pelicula',
            field=models.CharField(default='null', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='pelicula',
            field=models.CharField(max_length=60),
        ),
    ]
