# Generated by Django 4.0.4 on 2022-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_mensaje_clase_mensaje_pelicula_alter_pelicula_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='editado',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posteo',
            name='editado',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
