# Generated by Django 4.0.4 on 2022-06-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_mensaje_editado_posteo_editado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='avatar',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='id_avatar',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
