# Generated by Django 4.0.4 on 2022-06-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_remove_mensaje_avatar_mensaje_id_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='id_avatar',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='avatar',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
