# Generated by Django 4.0.4 on 2022-06-22 03:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_alter_posteo_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='trama_larga',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
